config/routes.rb
Rails.application.routes.draw do
  get 'create' , to: 'pages#create'
  get 'update/:id' , to: 'pages#update'
  root 'pages#home'
  get 'details/:id' , to: 'pages#details'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def create
    @products = Product.new()
  end

  def update
   
  end

  def home
    @products = Product.all
  end

  def details
    @products = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/create.html.erb
<h1>New Product</h1>


<%= form_for @products do |i| %>
    <div>
        <%=i.label :Product_name %>
        <%=i.text_field :Product_name %>
        <%=i.label :Product_price %>
        <%=i.number_field :Product_price %><br>
    </div>
    <%= form.submit %>
<% end %>

app/views/pages/details.html.erb
<h1><u>Product Details</u></h1>

<h3>Product name :<%= @products.title%><br>
Product price :<%= @products.price%><br>
Product id :<%= @products.id%><br></h3>

<%= link_to "home" ,root_path%>

app/views/pages/home.html.erb
<h1>Productsssss Available</h1>

<div>
    <% @products.each_with_index  do |i,y|%>
    <h3><a href="details/<%= y+1%>"> <%= i.title%>
    </a></h3>
    <%# <%= link_to "details/:y+1" , details_path %>
    <%end%>
</div>

app/views/pages/update.html.erb
<h1>Pages#update</h1>